Bump supported ruby version
Follow 0d1b754d3a32c2e26e5f9ed21a02b74489c0910a

On ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20],
`bin/setup; rake` failed as below

```
install -c tmp/x86_64-darwin20/pathname/2.7.2/pathname.bundle lib/pathname.bundle
cp tmp/x86_64-darwin20/pathname/2.7.2/pathname.bundle tmp/x86_64-darwin20/stage/lib/pathname.bundle
Loaded suite /Users/kachick/.gem/ruby/2.7.2/gems/rake-13.0.3/lib/rake/rake_test_loader
Started
...............................................................................
...............................................................................
...............................................................................
..............................................E
===============================================================================
Error: test_ractor_shareable(TestPathnameRactor): NameError: undefined local variable or method `skip' for #<TestPathnameRactor:0x00007ff6c7a2d878>
/Users/kachick/repos/pathname/test/pathname/test_ractor.rb:7:in `setup'
===============================================================================

Finished in 0.196045 seconds.
-------------------------------------------------------------------------------
284 tests, 368 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
99.6479% passed
-------------------------------------------------------------------------------
1448.65 tests/s, 1877.12 assertions/s
rake aborted!
Command failed with status (1)
/Users/kachick/.gem/ruby/2.7.2/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```